DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list(
    item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    category grocery NOT NULL,
    price decimal(12,2) NOT NULL,
    date_added TIMESTAMP NOT NULL,
    checked BOOLEAN DEFAULT false NOT NULL

);